### ISSUE TITLE
60fps patch not applied

### ISSUE THREAD

**Issue by Dima353** [mrneo240/sm64-port#21]
I can't apply the 60fps patch for the PSP version. Error while modifying file "pc_main.c"
![Снимок экрана от 2021-09-14 17-29-11](https://user-images.githubusercontent.com/75039669/133277898-fe91dae4-3403-433e-b9bc-8fc3fa06df5a.png)

**Comment by mrneo240** [comment]
Please rewrite and test the patch then make a PR
