### ISSUE TITLE
Incorrect Shadow Shape of Characters

### ISSUE THREAD

**Issue by NABN00B** [mrneo240/sm64-port#25]
Mario's, Toads' and enemies' shadow is shaped only a quarter of a circle instead of a full circle.

![image](https://github.com/mrneo240/sm64-port/assets/22328803/e80d86a6-efee-428c-b274-48303a602fd4)

**Comment by Dima353** [comment]
Similar to: 
https://github.com/fgsfdsfgs/sm64-port/issues/83

**Comment by NABN00B** [comment]
> Similar to: [fgsfdsfgs#83](https://github.com/fgsfdsfgs/sm64-port/issues/83)

Not exactly. I opened this issue for the shadows. It just so happens that my screenshot is from an older build in which transparent textures hadn't been fixed yet.

**Comment by Dima353** [comment]
> Not exactly. I opened this issue for the shadows.


Here is a fix for the shadows:
https://github.com/mrneo240/sm64-port/tree/master/psp

https://github.com/mrneo240/sm64-port/blob/eae08f977dc53a1447bfcc849b7ae1c0315be714/README.md?plain=1#L45

![image](https://github.com/mrneo240/sm64-port/assets/75039669/e5e36088-ea7a-42a9-836c-ca9f623e5c1e)

**Comment by NABN00B** [comment]
Thanks! Closing this.
